### ISSUE TITLE
ActiveRecord::MultiparameterAssignmentErrors for datetime_select

### ISSUE THREAD

**Issue by ajaya** [brianjlandau/unobtrusive_date_picker#1]
in Rails 2.3.2

A plain old datetime_select ends up causing a 

<pre><code>
/vendor/rails/activerecord/lib/active_record/base.rb:3061:in `execute_callstack_for_multiparameter_attributes'                
/vendor/rails/activerecord/lib/active_record/base.rb:3022:in `assign_multiparameter_attributes'
/vendor/rails/activerecord/lib/active_record/base.rb:2749:in `attributes='
/vendor/rails/activerecord/lib/active_record/base.rb:2439:in `initialize'
</code></pre>

Error

**Comment by ajaya** [comment]
Did bit more debugging. Looking like constant missing.

<pre><code>
NameError: uninitialized constant ActionView::Helpers::DateTimeSelector::AM        from vendor/rails/activesupport/lib/active_support/dependencies.rb:105:in `const_missing'                             
        from vendor/plugins/unobtrusive_date_picker/lib/12_hour_time.rb:21:in `instantiate_time_object'        from vendor/rails/activerecord/lib/active_record/base.rb:3048:in `execute_callstack_for_multiparameter_attributes'
</code></pre>

**Comment by k2heikkila** [comment]
I'm also having a problem with this.  Has anyone found a solution?

**Comment by vidmantas** [comment]
Same problem here. Sad, but I had to remove this plugin because of this annoying issue

**Comment by ElChapitan** [comment]
I'm having this problem as well, is there any solution to it?

**Comment by edla** [comment]
same issue here

**Comment by ajaya** [comment]
Closing. We ain't in rails 2.3.2 anymore.
